# -*- coding: utf-8 -*-
"""humanfirewalltrial2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YmoWretcbe4geWuYmvJBXUQ6fjj6wIc4
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install librosa scikit-learn

from google.colab import drive
drive.mount('/content/drive')

# Quick test: list audio files
!ls /content/drive/MyDrive/COLAB/DATASET/REAL
!ls /content/drive/MyDrive/COLAB/DATASET/FAKE
!ls /content/drive/MyDrive/COLAB/DATASET/real
!ls /content/drive/MyDrive/COLAB/DATASET/fake

# Confirm librosa version
import librosa
print(librosa.__version__)



import os

real_path = "/content/drive/MyDrive/COLAB/DATASET/REAL"
fake_path = "/content/drive/MyDrive/COLAB/DATASET/FAKE"

print("REAL exists:", os.path.exists(real_path))
print("FAKE exists:", os.path.exists(fake_path))

import os
import glob
import librosa
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix
import joblib


#increased mfcc from 13 > 40
def extract_features_from_array(audio_data, sr, n_mfcc=40, n_fft=2048, hop_length=512):
    try:
        # MFCCs
        mfccs = librosa.feature.mfcc(y=audio_data, sr=sr, n_mfcc=n_mfcc, n_fft=n_fft, hop_length=hop_length)
        mfcc_mean = np.mean(mfccs.T, axis=0)

        # Chroma
        chroma = librosa.feature.chroma_stft(y=audio_data, sr=sr)
        chroma_mean = np.mean(chroma.T, axis=0)

        # Spectral contrast
        contrast = librosa.feature.spectral_contrast(y=audio_data, sr=sr)
        contrast_mean = np.mean(contrast.T, axis=0)

        # Combine all features
        combined = np.hstack([mfcc_mean, chroma_mean, contrast_mean])
        return combined
    except Exception as e:
        print(f"Error extracting features from audio array: {e}")
        return None


#data augmentation
def augment_audio(audio_data, sr):
    augmented = []
    min_length = sr // 10  # Minimum 0.1 seconds
    if len(audio_data) < min_length:
        print(f"Audio too short for augmentation, using original only")
        return [audio_data]

    augmented.append(audio_data)
    try:
        augmented.append(librosa.effects.pitch_shift(audio_data, sr=sr, n_steps=2))
        augmented.append(librosa.effects.time_stretch(audio_data, rate=1.1))
        augmented.append(librosa.effects.time_stretch(audio_data, rate=0.9))
    except Exception as e:
        print(f"Augmentation failed: {e}, using original only")
        return [audio_data]
    return augmented


def create_dataset(directory, label):
    X, y = [], []
    audio_files = glob.glob(os.path.join(directory, "*.wav"))
    print(f"Found {len(audio_files)} files in {directory}")

    for audio_path in audio_files:
        print(f"Processing: {audio_path}")  # Debug print
        try:
            audio_data, sr = librosa.load(audio_path, sr=None)
            augmented_audios = augment_audio(audio_data, sr)
            for idx, data in enumerate(augmented_audios):
                features = extract_features_from_array(data, sr)
                if features is not None:
                    X.append(features)
                    y.append(label)
                else:
                    print(f"Skipping augmented sample {idx} for {audio_path}: Feature extraction failed")
        except Exception as e:
            print(f"Skipping file {audio_path}: {e}")

    print("Number of samples extracted from", directory, ":", len(X))
    return X, y


def extract_features(audio_path, sr=None, n_mfcc=40, n_fft=2048, hop_length=512):
    try:
        audio_data, sr = librosa.load(audio_path, sr=sr)

        # MFCCs
        mfcc = librosa.feature.mfcc(y=audio_data, sr=sr, n_mfcc=n_mfcc, n_fft=n_fft, hop_length=hop_length)
        mfcc_mean = np.mean(mfcc.T, axis=0)

        # Chroma
        try:
            stft = np.abs(librosa.stft(audio_data))
            chroma = librosa.feature.chroma_stft(S=stft, sr=sr)
            chroma_mean = np.mean(chroma.T, axis=0)
        except Exception as e:
            print(f"Chroma extraction failed for {audio_path}: {e}")
            chroma_mean = np.zeros(12)  # Default value

        # Spectral contrast
        try:
            contrast = librosa.feature.spectral_contrast(S=stft, sr=sr)
            contrast_mean = np.mean(contrast.T, axis=0)
        except Exception as e:
            print(f"Spectral contrast extraction failed for {audio_path}: {e}")
            contrast_mean = np.zeros(7)  # Default value

        # Combine all features
        combined = np.hstack([mfcc_mean, chroma_mean, contrast_mean])
        return combined
    except Exception as e:
        print(f"Error extracting features from {audio_path}: {e}")
        return None




def train_model(X, y):
    unique_classes = np.unique(y)
    print("Unique classes in y_train:", unique_classes)


    if len(unique_classes) < 2:
        raise ValueError("At least 2 classes are required to train")


    class_counts = np.bincount(y)
    if np.min(class_counts) < 2:
        print("Combining both classes into one for training")
        X_train, y_train = X, y
        X_test, y_test = None, None
    else:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)


    if X_test is not None:
        X_test_scaled = scaler.transform(X_test)
        svm_classifier = SVC(kernel='rbf', C=10, gamma=0.01, random_state=42)
        svm_classifier.fit(X_train_scaled, y_train)
        y_pred = svm_classifier.predict(X_test_scaled)


        accuracy = accuracy_score(y_test, y_pred)
        confusion_mtx = confusion_matrix(y_test, y_pred)


        print("Accuracy:", accuracy)
        print("Confusion Matrix:")
        print(confusion_mtx)
    else:
        print("Train on all available data.")
        svm_classifier = SVC(kernel='rbf', C=10, gamma=0.01, random_state=42)
        svm_classifier.fit(X_train_scaled, y_train)


    model_filename = "/content/drive/MyDrive/COLAB/DATASET/model.pkl"
    scaler_filename = "/content/drive/MyDrive/COLAB/DATASET/scaler.pkl"
    joblib.dump(svm_classifier, model_filename)
    joblib.dump(scaler, scaler_filename)


def main():
    real_dir = "/content/drive/MyDrive/COLAB/DATASET/FAKE"
    fake_dir = "/content/drive/MyDrive/COLAB/DATASET/REAL"
    dataset3_dir = "/content/drive/MyDrive/COLAB/DATASET/real"  # Replace with actual path
    dataset4_dir = "/content/drive/MyDrive/COLAB/DATASET/fake"  # Replace with actual path


    X_real, y_real = create_dataset(real_dir, label=0)
    X_fake, y_fake = create_dataset(fake_dir, label=1)
    X_dataset3, y_dataset3 = create_dataset(dataset3_dir, label=2)
    X_dataset4, y_dataset4 = create_dataset(dataset4_dir, label=3)


    X = np.vstack((X_real, X_fake))
    y = np.hstack((y_real, y_fake))


    save_dir = "/content/drive/MyDrive/COLAB/DATASET"
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)


    np.save(os.path.join(save_dir, "X_features.npy"), X)
    np.save(os.path.join(save_dir, "y_labels.npy"), y)


    train_model(X, y)


if __name__ == "__main__":
    main()